### ISSUE TITLE
Error with last version of module for webtrees 2.0.x

### ISSUE THREAD

**Issue by Ziris85** [vesta-webtrees-2-custom-modules/vesta_personal_facts#82]
Hello,

I'm unsure if you intend to continue supporting the version of this module for the webtrees 2.0.x version family, but when I attempted to upgrade it to 2.1.2.1.0, it throws an error on my site (which is running webtrees 2.0.25):
```
[root@web familytree]# cat modules_v4/vesta_personal_facts/latest-version.txt
2.1.2.1.0
```
```
 Fatal error in module: vesta_personal_facts
ErrorException: Declaration of Cissee\Webtrees\Module\PersonalFacts\IndividualFactsTabModuleExtended_20::getOutputBeforeTab(Fisharebest\Webtrees\GedcomRecord $record) should be compatible with Cissee\WebtreesExt\Module\IndividualFactsTabModule_20::getOutputBeforeTab(Fisharebest\Webtrees\Individual $person) in /var/www/vestfarms/familytree/modules_v4/vesta_personal_facts/IndividualFactsTabModuleExtended_20.php:54 
Stack trace: 
#0 /var/www/vestfarms/familytree/modules_v4/vesta_personal_facts/IndividualFactsTabModuleExtended_20.php(54): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(2, 'Declaration of ...', '/var/www/vestfa...', 54, Array) 
#1 /var/www/vestfarms/familytree/vendor/composer/ClassLoader.php(571): include('/var/www/vestfa...') 
#2 /var/www/vestfarms/familytree/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/vestfa...') 
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Cissee\\Webtrees...') 
#4 [internal function]: spl_autoload_call('Cissee\\Webtrees...') 
#5 /var/www/vestfarms/familytree/vendor/illuminate/container/Container.php(788): ReflectionClass->__construct('Cissee\\Webtrees...') 
#6 /var/www/vestfarms/familytree/vendor/illuminate/container/Container.php(667): Illuminate\Container\Container->build('Cissee\\Webtrees...') 
#7 /var/www/vestfarms/familytree/vendor/illuminate/container/Container.php(615): Illuminate\Container\Container->resolve('Cissee\\Webtrees...', Array) 
#8 /var/www/vestfarms/familytree/app/Webtrees.php(288): Illuminate\Container\Container->make('Cissee\\Webtrees...') 
#9 /var/www/vestfarms/familytree/app/Helpers/functions.php(44): Fisharebest\Webtrees\Webtrees::make('Cissee\\Webtrees...') 
#10 /var/www/vestfarms/familytree/modules_v4/vesta_personal_facts/module.php(59): app('Cissee\\Webtrees...') 
#11 /var/www/vestfarms/familytree/app/Services/ModuleService.php(691): include('/var/www/vestfa...') 
#12 /var/www/vestfarms/familytree/app/Services/ModuleService.php(642): Fisharebest\Webtrees\Services\ModuleService::load('/var/www/vestfa...') 
#13 [internal function]: Fisharebest\Webtrees\Services\ModuleService::Fisharebest\Webtrees\Services\{closure}('/var/www/vestfa...', 21) 
#14 /var/www/vestfarms/familytree/vendor/illuminate/support/Collection.php(1120): array_map(Object(Closure), Array, Array) 
#15 /var/www/vestfarms/familytree/app/Services/ModuleService.php(658): Illuminate\Support\Collection->map(Object(Closure)) 
#16 /var/www/vestfarms/familytree/app/Services/ModuleService.php(563): Fisharebest\Webtrees\Services\ModuleService->customModules() 
#17 /var/www/vestfarms/familytree/app/Cache.php(59): Fisharebest\Webtrees\Services\ModuleService->Fisharebest\Webtrees\Services\{closure}() 
#18 /var/www/vestfarms/familytree/vendor/symfony/cache/Adapter/ArrayAdapter.php(63): Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}(Object(Symfony\Component\Cache\CacheItem), true) 
#19 /var/www/vestfarms/familytree/app/Cache.php(60): Symfony\Component\Cache\Adapter\ArrayAdapter->get('372b64b23390f9d...', Object(Closure)) 
#20 /var/www/vestfarms/familytree/app/Services/ModuleService.php(596): Fisharebest\Webtrees\Cache->remember('all-modules', Object(Closure)) 
#21 /var/www/vestfarms/familytree/app/Services/ModuleService.php(519): Fisharebest\Webtrees\Services\ModuleService->all(true) 
#22 /var/www/vestfarms/familytree/app/Http/Middleware/UseLanguage.php(83): Fisharebest\Webtrees\Services\ModuleService->findByInterface('Fisharebest\\Web...', true) 
#23 /var/www/vestfarms/familytree/app/Http/Middleware/UseLanguage.php(62): Fisharebest\Webtrees\Http\Middleware\UseLanguage->languages(Object(Nyholm\Psr7\ServerRequest)) 
#24 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#25 /var/www/vestfarms/familytree/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#26 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#27 /var/www/vestfarms/familytree/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#28 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#29 /var/www/vestfarms/familytree/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#30 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#31 /var/www/vestfarms/familytree/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#32 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#33 /var/www/vestfarms/familytree/app/Http/Middleware/BadBotBlocker.php(223): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#34 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#35 /var/www/vestfarms/familytree/app/Http/Middleware/CompressResponse.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#36 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#37 /var/www/vestfarms/familytree/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#38 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#39 /var/www/vestfarms/familytree/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#40 /var/www/vestfarms/familytree/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#41 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#42 /var/www/vestfarms/familytree/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#43 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#44 /var/www/vestfarms/familytree/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#45 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#46 /var/www/vestfarms/familytree/app/Http/Middleware/ReadConfigIni.php(69): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#47 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#48 /var/www/vestfarms/familytree/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#49 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#50 /var/www/vestfarms/familytree/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#51 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) 
#52 /var/www/vestfarms/familytree/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) 
#53 /var/www/vestfarms/familytree/app/Webtrees.php(241): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) 
#54 /var/www/vestfarms/familytree/app/Webtrees.php(228): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array) 
#55 /var/www/vestfarms/familytree/index.php(44): Fisharebest\Webtrees\Webtrees->httpRequest() 
#56 {main}
```
I do intend to upgrade to webtrees 2.1 soon-ish, but for now just keeping things up-to-date on what I have currently.

Thanks!

**Comment by Ziris85** [comment]
Yep! That's where I downloaded it (and the rest of the modules) from.

**Comment by ric2016** [comment]
[This should be ok in php 7.4](https://stitcher.io/blog/new-in-php-74#improved-type-variance-rfc), so I assume you're using an older php version?

Anyway, I created a new "final" release where this issue should be fixed (there may be others though). In any case I recommend to upgrade to php 7.4 and webtrees 2.1 as soon as possible.

**Comment by Ziris85** [comment]
Right again - I'm running 7.3 currently. I just tried tried the new version and it works great - thanks! Yep, an upgrade is definitely on my radar. When life gives me the time to do it heh...thanks again :)
